name: viz
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - altair=4.1.0
  - anyio=3.2.1
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow-cpp=4.0.1
  - astor=0.8.1
  - async_generator=1.10
  - attrs=21.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - base58=2.1.0
  - black=21.7b0
  - bleach=3.3.1
  - blinker=1.4
  - boto3=1.18.1
  - botocore=1.21.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=7.1.2
  - cryptography=3.4.7
  - dataclasses=0.8
  - debugpy=1.3.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.18
  - glog=0.5.0
  - greenlet=1.1.0
  - grpc-cpp=1.38.1
  - idna=3.1
  - importlib-metadata=4.6.1
  - ipykernel=6.0.2
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jmespath=0.10.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.9.0
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.1
  - jupyterlab_widgets=1.0.0
  - krb5=1.19.1
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libthrift=0.14.2
  - libtiff=4.3.0
  - libutf8proc=2.6.1
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - numpy=1.21.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - orc=1.6.9
  - packaging=21.0
  - pandas=1.3.0
  - pandoc=2.14.0.3
  - pandocfilters=1.4.2
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - pathspec=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.1.3
  - plotly=5.1.0
  - plotly-geo=1.0.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - protobuf=3.16.0
  - ptyprocess=0.7.0
  - pyarrow=4.0.1
  - pycparser=2.20
  - pydeck=0.6.2
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.1.0
  - re2=2021.06.01
  - readline=8.1
  - regex=2021.7.6
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - s3transfer=0.5.0
  - send2trash=1.7.1
  - setuptools=49.6.0
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlalchemy=1.4.21
  - sqlite=3.36.0
  - streamlit=0.84.1
  - tenacity=8.0.1
  - terminado=0.10.1
  - testpath=0.5.0
  - tk=8.6.10
  - toml=0.10.2
  - tomli=1.0.4
  - tomlkit=0.7.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - tzlocal=2.1
  - urllib3=1.26.6
  - validators=0.18.2
  - watchdog=2.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
